// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'models/image_meta.dart';
import 'models/post.dart';
import 'models/tag.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5163123535892336562),
    name: 'Tag',
    lastPropertyId: const obx_int.IdUid(2, 595672351960101895),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5527304652252315859),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 595672351960101895),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4843656409920837308),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3090353901879372909),
    name: 'ImageMeta',
    lastPropertyId: const obx_int.IdUid(3, 2162218059161696701),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1215240304155563311),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6228964843602763671),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2162218059161696701),
        name: 'postId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 6092278765806091523),
        relationField: 'post',
        relationTarget: 'Post',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1551219590584248299),
    name: 'Post',
    lastPropertyId: const obx_int.IdUid(5, 1284081191498630664),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1110564005166846947),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7881841992744921427),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5903341050497116593),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8188533964532363312),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1284081191498630664),
        name: 'isDeleted',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(3, 7031885950109081293),
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 357296839644546150),
        name: 'tags',
        targetId: const obx_int.IdUid(1, 5163123535892336562),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'images',
        srcEntity: 'ImageMeta',
        srcField: 'post',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1551219590584248299),
    lastIndexId: const obx_int.IdUid(3, 7031885950109081293),
    lastRelationId: const obx_int.IdUid(1, 357296839644546150),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Tag: obx_int.EntityDefinition<Tag>(
      model: _entities[0],
      toOneRelations: (Tag object) => [],
      toManyRelations: (Tag object) => {},
      getId: (Tag object) => object.id,
      setId: (Tag object, int id) {
        object.id = id;
      },
      objectToFB: (Tag object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Tag(id: idParam, name: nameParam);

        return object;
      },
    ),
    ImageMeta: obx_int.EntityDefinition<ImageMeta>(
      model: _entities[1],
      toOneRelations: (ImageMeta object) => [object.post],
      toManyRelations: (ImageMeta object) => {},
      getId: (ImageMeta object) => object.id,
      setId: (ImageMeta object, int id) {
        object.id = id;
      },
      objectToFB: (ImageMeta object, fb.Builder fbb) {
        final localPathOffset = fbb.writeString(object.localPath);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, localPathOffset);
        fbb.addInt64(2, object.post.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = ImageMeta(id: idParam, localPath: localPathParam);
        object.post.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.post.attach(store);
        return object;
      },
    ),
    Post: obx_int.EntityDefinition<Post>(
      model: _entities[2],
      toOneRelations: (Post object) => [],
      toManyRelations: (Post object) => {
        obx_int.RelInfo<Post>.toMany(1, object.id): object.tags,
        obx_int.RelInfo<ImageMeta>.toOneBacklink(
          3,
          object.id,
          (ImageMeta srcObject) => srcObject.post,
        ): object.images,
      },
      getId: (Post object) => object.id,
      setId: (Post object, int id) {
        object.id = id;
      },
      objectToFB: (Post object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addInt64(3, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(4, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = Post(
          id: idParam,
          uuid: uuidParam,
          content: contentParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Post>(
          object.tags,
          store,
          obx_int.RelInfo<Post>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Post>(
          object.images,
          store,
          obx_int.RelInfo<ImageMeta>.toOneBacklink(
            3,
            object.id,
            (ImageMeta srcObject) => srcObject.post,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Tag] entity fields to define ObjectBox queries.
class Tag_ {
  /// See [Tag.id].
  static final id = obx.QueryIntegerProperty<Tag>(_entities[0].properties[0]);

  /// See [Tag.name].
  static final name = obx.QueryStringProperty<Tag>(_entities[0].properties[1]);
}

/// [ImageMeta] entity fields to define ObjectBox queries.
class ImageMeta_ {
  /// See [ImageMeta.id].
  static final id = obx.QueryIntegerProperty<ImageMeta>(
    _entities[1].properties[0],
  );

  /// See [ImageMeta.localPath].
  static final localPath = obx.QueryStringProperty<ImageMeta>(
    _entities[1].properties[1],
  );

  /// See [ImageMeta.post].
  static final post = obx.QueryRelationToOne<ImageMeta, Post>(
    _entities[1].properties[2],
  );
}

/// [Post] entity fields to define ObjectBox queries.
class Post_ {
  /// See [Post.id].
  static final id = obx.QueryIntegerProperty<Post>(_entities[2].properties[0]);

  /// See [Post.uuid].
  static final uuid = obx.QueryStringProperty<Post>(_entities[2].properties[1]);

  /// See [Post.content].
  static final content = obx.QueryStringProperty<Post>(
    _entities[2].properties[2],
  );

  /// See [Post.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Post>(
    _entities[2].properties[3],
  );

  /// See [Post.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Post>(
    _entities[2].properties[4],
  );

  /// see [Post.tags]
  static final tags = obx.QueryRelationToMany<Post, Tag>(
    _entities[2].relations[0],
  );

  /// see [Post.images]
  static final images = obx.QueryBacklinkToMany<ImageMeta, Post>(
    ImageMeta_.post,
  );
}
