/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MynotesSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  serverAddress: "http://192.168.1.100:8080",
  apiToken: "",
  targetVaultFolder: "",
  useRemoteImages: false
};
var MynotesSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Mynotes Sync \u2014 \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("Server Address").setDesc("\u5C40\u57DF\u7F51\u540C\u6B65\u670D\u52A1\u5668\u7684\u5730\u5740\uFF0C\u4F8B\u5982 http://192.168.1.100:8080").addText(
      (text) => text.setPlaceholder("http://192.168.1.100:8080").setValue(this.plugin.settings.serverAddress).onChange(async (value) => {
        this.plugin.settings.serverAddress = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API Token").setDesc("\u7528\u4E8E Bearer \u9274\u6743\u7684\u4EE4\u724C\uFF08\u5BC6\u7801\u5B57\u6BB5\uFF0C\u4EC5\u672C\u5730\u5B58\u50A8\uFF09").addText((text) => {
      text.setPlaceholder("\u8F93\u5165 API Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Target Vault Folder").setDesc("\u540C\u6B65\u76EE\u6807\u6587\u4EF6\u5939\u8DEF\u5F84\uFF08\u76F8\u5BF9\u4E8E\u5E93\u6839\u76EE\u5F55\uFF09\uFF0C\u7559\u7A7A\u8868\u793A\u6839\u76EE\u5F55").addText(
      (text) => text.setPlaceholder("Mynotes/").setValue(this.plugin.settings.targetVaultFolder).onChange(async (value) => {
        this.plugin.settings.targetVaultFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Use Remote Images").setDesc("\u5F00\u542F\u540E\u4F18\u5148\u4F7F\u7528\u7F51\u7EDC\u56FE\u5E8A URL \u5C55\u793A\u56FE\u7247\uFF0C\u5173\u95ED\u5219\u4F7F\u7528\u672C\u5730\u8D44\u6E90").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useRemoteImages).onChange(async (value) => {
        this.plugin.settings.useRemoteImages = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/syncEngine.ts
var import_obsidian2 = require("obsidian");
function pad(n) {
  return n.toString().padStart(2, "0");
}
function formatDate(input) {
  const d = new Date(input);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}
function getDayKey(input) {
  const d = new Date(input);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
async function fetchSyncData(serverAddress, apiToken) {
  const resp = await (0, import_obsidian2.requestUrl)({
    url: `${serverAddress.replace(/\/+$/, "")}/api/sync`,
    method: "GET",
    headers: {
      Authorization: `Bearer ${apiToken}`,
      "Content-Type": "application/json"
    }
  });
  return resp.json;
}
var IMAGES_FOLDER = "assets";
function extractFileName(localPath) {
  var _a;
  const segments = localPath.split(/[/\\]/);
  return (_a = segments[segments.length - 1]) != null ? _a : "image.jpg";
}
async function downloadAsset(serverAddress, apiToken, localPath) {
  var _a;
  const serverBase = serverAddress.replace(/\/+$/, "");
  const encodedPath = encodeURIComponent(localPath);
  const imgUrl = `${serverBase}/api/assets?path=${encodedPath}`;
  console.log(`[MynotesSync] \u4E0B\u8F7D\u56FE\u7247: ${imgUrl}`);
  try {
    const resp = await (0, import_obsidian2.requestUrl)({
      url: imgUrl,
      headers: { Authorization: `Bearer ${apiToken}` },
      throw: false
    });
    console.log(`[MynotesSync] \u56FE\u7247\u54CD\u5E94: status=${resp.status}, arrayBuffer=${!!resp.arrayBuffer}, length=${(_a = resp.arrayBuffer) == null ? void 0 : _a.byteLength}`);
    if (resp.status === 200 && resp.arrayBuffer) {
      return resp.arrayBuffer;
    }
    console.warn(`[MynotesSync] /api/assets \u54CD\u5E94\u5F02\u5E38 status=${resp.status} path=${localPath}`);
    return null;
  } catch (e) {
    console.error(`[MynotesSync] \u4E0B\u8F7D\u56FE\u7247\u5931\u8D25: ${localPath}`, e);
    return null;
  }
}
async function ensureImagesFolder(plugin) {
  const targetFolder = plugin.settings.targetVaultFolder.replace(/^\/|\/$/g, "") || "";
  const folderPath = targetFolder ? `${targetFolder}/${IMAGES_FOLDER}` : IMAGES_FOLDER;
  const existing = plugin.app.vault.getAbstractFileByPath(folderPath);
  if (!existing) {
    await plugin.app.vault.createFolder(folderPath);
  }
}
async function downloadAndSaveImage(plugin, serverAddress, apiToken, img, existingImagePaths) {
  const targetFolder = plugin.settings.targetVaultFolder.replace(/^\/|\/$/g, "") || "";
  const folderPath = targetFolder ? `${targetFolder}/${IMAGES_FOLDER}` : IMAGES_FOLDER;
  const fileName = extractFileName(img.localPath);
  const imgPath = `${folderPath}/${fileName}`;
  console.log(`[MynotesSync] \u5904\u7406\u56FE\u7247: localPath=${img.localPath} -> ${imgPath}`);
  if (existingImagePaths.has(imgPath)) {
    console.log(`[MynotesSync] \u56FE\u7247\u5DF2\u5B58\u5728\uFF0C\u8DF3\u8FC7: ${imgPath}`);
    return `![[${IMAGES_FOLDER}/${fileName}]]`;
  }
  const arrayBuffer = await downloadAsset(serverAddress, apiToken, img.localPath);
  if (!arrayBuffer) {
    console.warn(`[MynotesSync] \u56FE\u7247\u4E0B\u8F7D\u5931\u8D25\uFF0C\u65E0\u6CD5\u4FDD\u5B58: ${imgPath}`);
    return "";
  }
  try {
    await plugin.app.vault.createBinary(imgPath, arrayBuffer);
    console.log(`[MynotesSync] \u56FE\u7247\u5DF2\u4FDD\u5B58: ${imgPath} (${arrayBuffer.byteLength} bytes)`);
    return `![[${IMAGES_FOLDER}/${fileName}]]`;
  } catch (e) {
    console.error(`[MynotesSync] \u5199\u5165\u56FE\u7247\u5931\u8D25: ${imgPath}`, e);
    return "";
  }
}
function generateDailyMarkdown(dayKey, posts, imageLinks) {
  var _a;
  const sorted = [...posts].sort(
    (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
  );
  const tagSet = /* @__PURE__ */ new Set();
  for (const post of sorted) {
    for (const tag of post.tags)
      tagSet.add(tag);
  }
  const tags = [...tagSet].sort();
  const safe = (s) => s.replace(/"/g, '\\"');
  let fm = "---\n";
  fm += `date: "${dayKey}"
`;
  if (tags.length > 0) {
    fm += "tags:\n";
    for (const tag of tags)
      fm += `  - "${safe(tag)}"
`;
  }
  fm += "---\n\n";
  let body = "";
  for (const post of sorted) {
    const timeStr = formatDate(post.createdAt).split(" ")[1];
    body += `### ${timeStr}

`;
    const trimmed = post.content.trim();
    if (trimmed) {
      body += trimmed + "\n\n";
    }
    const links = (_a = imageLinks.get(post.uuid)) != null ? _a : [];
    for (const link of links) {
      if (link)
        body += `${link}
`;
    }
    body += "\n";
  }
  return fm + body.trim();
}
async function executeSync(plugin) {
  var _a;
  const { settings, app } = plugin;
  if (!settings.serverAddress) {
    new import_obsidian2.Notice("Mynotes Sync: \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E Server Address");
    return;
  }
  const statusBarEl = plugin.addStatusBarItem();
  const setStatus = (msg) => statusBarEl.setText(msg);
  setStatus("Mynotes Sync: \u8FDE\u63A5\u4E2D\u2026");
  try {
    setStatus("Mynotes Sync: \u62C9\u53D6\u6570\u636E\u4E2D\u2026");
    const posts = await fetchSyncData(settings.serverAddress, settings.apiToken);
    if (posts.length === 0) {
      new import_obsidian2.Notice("Mynotes Sync: \u6CA1\u6709\u9700\u8981\u540C\u6B65\u7684\u6570\u636E");
      return;
    }
    const dayGroups = /* @__PURE__ */ new Map();
    for (const post of posts) {
      const dayKey = getDayKey(post.createdAt);
      if (!dayGroups.has(dayKey))
        dayGroups.set(dayKey, []);
      dayGroups.get(dayKey).push(post);
    }
    const dayKeys = [...dayGroups.keys()].sort();
    console.log(`[MynotesSync] \u5171\u6709 ${dayKeys.length} \u5929\u7684\u6570\u636E`);
    const folderPath = settings.targetVaultFolder.replace(/^\/|\/$/g, "") || "";
    const ensureFolder = async (path) => {
      const existing = app.vault.getAbstractFileByPath(path);
      if (!existing)
        await app.vault.createFolder(path);
    };
    if (folderPath)
      await ensureFolder(folderPath);
    await ensureImagesFolder(plugin);
    const existingImagePaths = /* @__PURE__ */ new Set();
    const imagesFolder = folderPath ? `${folderPath}/${IMAGES_FOLDER}` : IMAGES_FOLDER;
    for (const file of app.vault.getFiles()) {
      if (file.path.startsWith(imagesFolder + "/")) {
        existingImagePaths.add(file.path);
      }
    }
    const imageLinksMap = /* @__PURE__ */ new Map();
    for (const post of posts) {
      const links = [];
      for (const img of post.images) {
        if (!img.localPath)
          continue;
        const link = await downloadAndSaveImage(
          plugin,
          settings.serverAddress,
          settings.apiToken,
          img,
          existingImagePaths
        );
        if (link) {
          existingImagePaths.add(
            `${imagesFolder}/${extractFileName(img.localPath)}`
          );
        }
        links.push(link);
      }
      imageLinksMap.set(post.uuid, links);
    }
    let synced = 0;
    let skipped = 0;
    for (const dayKey of dayKeys) {
      const dayPosts = dayGroups.get(dayKey);
      const fileName = `${dayKey}.md`;
      const filePath = folderPath ? `${folderPath}/${fileName}` : fileName;
      const content = generateDailyMarkdown(dayKey, dayPosts, imageLinksMap);
      const existing = app.vault.getAbstractFileByPath(filePath);
      if (existing instanceof import_obsidian2.TFile) {
        const cache = app.metadataCache.getFileCache(existing);
        const localDate = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.date;
        if (localDate) {
          const localTs = new Date(localDate).getTime();
          const remoteTs = new Date(dayKey).getTime();
          if (remoteTs > localTs) {
            await app.vault.modify(existing, content);
            synced++;
          } else {
            skipped++;
          }
        } else {
          await app.vault.modify(existing, content);
          synced++;
        }
      } else {
        await app.vault.create(filePath, content);
        synced++;
      }
      setStatus(`Mynotes Sync: ${synced + skipped}/${dayKeys.length} \u5929`);
    }
    new import_obsidian2.Notice(`Mynotes Sync: \u540C\u6B65\u5B8C\u6210 \u2014 ${dayKeys.length} \u5929`);
  } catch (error) {
    new import_obsidian2.Notice(`Mynotes Sync: \u540C\u6B65\u5931\u8D25 \u2014 ${error.message}`);
  } finally {
    statusBarEl.remove();
  }
}

// src/main.ts
var MynotesSyncPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MynotesSyncSettingTab(this.app, this));
    this.addRibbonIcon("cloud", "Mynotes Sync \u2014 \u89E6\u53D1\u540C\u6B65", () => {
      executeSync(this);
    });
    this.addCommand({
      id: "trigger-sync",
      name: "\u89E6\u53D1\u540C\u6B65",
      callback: () => {
        executeSync(this);
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
