/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MynotesSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  serverAddress: "http://192.168.1.100:8080",
  apiToken: "",
  targetVaultFolder: "",
  useRemoteImages: false
};
var MynotesSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Mynotes Sync \u2014 \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("Server Address").setDesc("\u5C40\u57DF\u7F51\u540C\u6B65\u670D\u52A1\u5668\u7684\u5730\u5740\uFF0C\u4F8B\u5982 http://192.168.1.100:8080").addText(
      (text) => text.setPlaceholder("http://192.168.1.100:8080").setValue(this.plugin.settings.serverAddress).onChange(async (value) => {
        this.plugin.settings.serverAddress = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API Token").setDesc("\u7528\u4E8E Bearer \u9274\u6743\u7684\u4EE4\u724C\uFF08\u5BC6\u7801\u5B57\u6BB5\uFF0C\u4EC5\u672C\u5730\u5B58\u50A8\uFF09").addText((text) => {
      text.setPlaceholder("\u8F93\u5165 API Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Target Vault Folder").setDesc("\u540C\u6B65\u76EE\u6807\u6587\u4EF6\u5939\u8DEF\u5F84\uFF08\u76F8\u5BF9\u4E8E\u5E93\u6839\u76EE\u5F55\uFF09\uFF0C\u7559\u7A7A\u8868\u793A\u6839\u76EE\u5F55").addText(
      (text) => text.setPlaceholder("Mynotes/").setValue(this.plugin.settings.targetVaultFolder).onChange(async (value) => {
        this.plugin.settings.targetVaultFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Use Remote Images").setDesc("\u5F00\u542F\u540E\u4F18\u5148\u4F7F\u7528\u7F51\u7EDC\u56FE\u5E8A URL \u5C55\u793A\u56FE\u7247\uFF0C\u5173\u95ED\u5219\u4F7F\u7528\u672C\u5730\u8D44\u6E90").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useRemoteImages).onChange(async (value) => {
        this.plugin.settings.useRemoteImages = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/syncEngine.ts
var import_obsidian2 = require("obsidian");
function pad(n) {
  return n.toString().padStart(2, "0");
}
function formatDate(input) {
  const d = new Date(input);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}
function formatDateForFile(input) {
  const d = new Date(input);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
async function fetchSyncData(serverAddress, apiToken) {
  const resp = await (0, import_obsidian2.requestUrl)({
    url: `${serverAddress.replace(/\/+$/, "")}/api/sync`,
    method: "GET",
    headers: {
      Authorization: `Bearer ${apiToken}`,
      "Content-Type": "application/json"
    }
  });
  return resp.json;
}
function generateMarkdown(post, settings) {
  const date = formatDate(post.createdAt);
  const updated = formatDate(post.updatedAt);
  const safe = (s) => s.replace(/"/g, '\\"');
  let fm = "---\n";
  fm += `uuid: "${safe(post.uuid)}"
`;
  fm += `date: "${date}"
`;
  fm += `updated: "${updated}"
`;
  fm += "tags:\n";
  for (const tag of post.tags) {
    fm += `  - "${safe(tag)}"
`;
  }
  fm += "---\n\n";
  let body = post.content;
  for (const img of post.images) {
    if (img.downloadUrl && img.localPath) {
      const fileName = img.localPath.split("/").pop() || `${post.uuid}.jpg`;
      body += `
![[${fileName}]]`;
    } else if (settings.useRemoteImages && img.remoteUrl) {
      body += `
![image](${img.remoteUrl})`;
    }
  }
  return fm + body;
}
async function executeSync(plugin) {
  var _a;
  const { settings, app } = plugin;
  if (!settings.serverAddress) {
    new import_obsidian2.Notice("Mynotes Sync: \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E Server Address");
    return;
  }
  const statusBarEl = plugin.addStatusBarItem();
  const setStatus = (msg) => statusBarEl.setText(msg);
  setStatus("Mynotes Sync: \u8FDE\u63A5\u4E2D\u2026");
  try {
    setStatus("Mynotes Sync: \u62C9\u53D6\u6570\u636E\u4E2D\u2026");
    const posts = await fetchSyncData(settings.serverAddress, settings.apiToken);
    const total = posts.length;
    if (total === 0) {
      new import_obsidian2.Notice("Mynotes Sync: \u6CA1\u6709\u9700\u8981\u540C\u6B65\u7684\u6570\u636E");
      return;
    }
    const folderPath = settings.targetVaultFolder.replace(/^\/|\/$/g, "") || "";
    const imagesFolder = folderPath ? `${folderPath}/.mynotes-images` : ".mynotes-images";
    const ensureFolder = async (path) => {
      const existing = app.vault.getAbstractFileByPath(path);
      if (!existing) {
        await app.vault.createFolder(path);
      }
    };
    if (folderPath) {
      await ensureFolder(folderPath);
    }
    await ensureFolder(imagesFolder);
    let synced = 0;
    let skipped = 0;
    for (let i = 0; i < total; i++) {
      const post = posts[i];
      const fileName = `${formatDateForFile(post.createdAt)}.md`;
      const filePath = folderPath ? `${folderPath}/${fileName}` : fileName;
      const content = generateMarkdown(post, settings);
      const existing = app.vault.getAbstractFileByPath(filePath);
      if (existing instanceof import_obsidian2.TFile) {
        const cache = app.metadataCache.getFileCache(existing);
        const localUpdated = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.updated;
        if (localUpdated) {
          const localTs = new Date(localUpdated).getTime();
          const remoteTs = new Date(post.updatedAt).getTime();
          if (remoteTs > localTs) {
            await app.vault.modify(existing, content);
            synced++;
          } else {
            skipped++;
          }
        } else {
          await app.vault.modify(existing, content);
          synced++;
        }
      } else {
        await app.vault.create(filePath, content);
        synced++;
      }
      for (const img of post.images) {
        if (!img.downloadUrl || !img.localPath)
          continue;
        const fileName2 = img.localPath.split("/").pop() || `${post.uuid}.jpg`;
        const imgPath = `${imagesFolder}/${fileName2}`;
        const imgExisting = app.vault.getAbstractFileByPath(imgPath);
        if (!(imgExisting instanceof import_obsidian2.TFile)) {
          const serverBase = settings.serverAddress.replace(/\/+$/, "");
          const imgUrl = `${serverBase}${img.downloadUrl}`;
          try {
            const resp = await (0, import_obsidian2.requestUrl)({
              url: imgUrl,
              headers: { Authorization: `Bearer ${settings.apiToken}` }
            });
            const imgData = resp.arrayBuffer;
            await app.vault.createBinary(imgPath, imgData);
          } catch (e) {
          }
        }
      }
      setStatus(`Mynotes Sync: ${synced + skipped}/${total}`);
    }
    new import_obsidian2.Notice(`Mynotes Sync: \u540C\u6B65\u5B8C\u6210 \u2014 \u65B0\u589E/\u66F4\u65B0 ${synced} \u6761\uFF0C\u8DF3\u8FC7 ${skipped} \u6761`);
  } catch (error) {
    new import_obsidian2.Notice(`Mynotes Sync: \u540C\u6B65\u5931\u8D25 \u2014 ${error.message}`);
  } finally {
    statusBarEl.remove();
  }
}

// src/main.ts
var MynotesSyncPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MynotesSyncSettingTab(this.app, this));
    this.addRibbonIcon("cloud", "Mynotes Sync \u2014 \u89E6\u53D1\u540C\u6B65", () => {
      executeSync(this);
    });
    this.addCommand({
      id: "trigger-sync",
      name: "\u89E6\u53D1\u540C\u6B65",
      callback: () => {
        executeSync(this);
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
